### ISSUE TITLE
[Bug]: Playlist shuffle only queues first 10th of songs

### ISSUE THREAD

**Issue by NicoAFlorez** [ciderapp/Cider#1107]
### Describe the Bug

I have a large playlist alphebatized by album name, whenever i shuffle the playlist only albums that start with a will be queued.

### Steps to Reproduce

1. shuffled a playlist

### Environment Information

- OS: windows 10
- App Version and/or Commit ID: windows store

### Anything else?

![image](https://user-images.githubusercontent.com/94549692/171521930-72fb0bde-14cd-4d46-9ae0-4dfa73723c35.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vitormarambaia** [comment]
The same happens to me, using Flatpak on Ubuntu 20.04

**Comment by nate-thegrate** [comment]
I'd like to share some details I've learned via personal testing.

![shuffle toggle](https://user-images.githubusercontent.com/10457200/177649088-63fb74c8-e33c-4c33-83a1-25ad8bfdc9ec.png) Shuffle toggle (top left of the screen): works exactly as it should. If the shuffle toggle is active, playing a song from a playlist will queue up a bunch of random songs from that playlist.

![shuffle button](https://user-images.githubusercontent.com/10457200/177649306-c3f4d48c-502b-4540-b6a7-4f76b437c6be.png) Shuffle button: Instead of completely shuffling the playlist, it will play the first 100 songs in a random order and then will start playing other songs.  
So if your playlist starts with 25 songs by Ed Sheeran and 75 songs by The Beatles, it'll only play Ed Sheeran and Beatles for the first 100 songs (after which it will shuffle like it should).

**Comment by nate-thegrate** [comment]
Leaving a comment here to remove the "stale" label.  
It's only a minor inconvenience, but it'd be great if the Shuffle button worked properly.

**Comment by LykosYT** [comment]
I would really like to have a real shuffle button yeah... I've been using Apple Music app more than Cider because of this

**Comment by nate-thegrate** [comment]
making another comment here lol

**Comment by cryptofyre** [comment]
Apple just treats this function differently, it does it on everything but their native apps for whatever reason and there isn't much we can do but to suggest creating feedback on MusicKit on something like the Feedback app or service.

Closing.
