### ISSUE TITLE
[Bug]: Weird text in album name

### ISSUE THREAD

**Issue by Croldfish** [ciderapp/Cider#1570]
### Describe the Bug

When in Mojave preset (in visual settings), the text for the alumn name is crumbly (I don't have a better word to describe it sorry)
![Screenshot from 2022-11-18 12-25-11](https://user-images.githubusercontent.com/70867293/202765521-b7f7fe41-4c92-4c47-8b56-1e402744332f.png)

### Steps to Reproduce

1. Enable Mojave window style
2. Look at the bottom right corner at the albumn name
3. boom

### Environment Information

- OS:Fedora linux 36
- Desktop Environment:  GNOME
- App Version: 1.5.9
- Commit ID: I have no idea what this is but it's the latest version of cider (stable) on flathub

### How did you download the software?

Flathub

### Anything else?

This is maybe my second time submitting a bug report to any project on github, sorry if it seems unprofessional. 

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by somekdeguy** [comment]
same here on fedora 37 with KDE, also running the flatpak.

**Comment by ilian002** [comment]
I have the same issue on TUXEDO OS 1 (ubuntu jammy based), also running the flatpak.
The issue seems to be related to global scaling. At 100% scaling the text is rendered correctly.

100%: <img src="https://user-images.githubusercontent.com/120368121/210074138-85cf944f-7ed5-443c-8343-807e0268380c.png" width="400"> 
200%: <img src="https://user-images.githubusercontent.com/120368121/210074107-b8562851-c7f5-4076-91f3-123226cee8ba.png" width="400"> 
300%: <img src="https://user-images.githubusercontent.com/120368121/210074118-5648729e-e833-4616-bae8-a702374779ba.png" width="400">



Kernel: 6.0.0-1006-oem 
Resolution: 2880x1800 
DE: Plasma 5.24.7 
WM: KWin
