### ISSUE TITLE
[Bug]: Home page doesn't load, can't create new playlists, and can't heart/like songs...

### ISSUE THREAD

**Issue by bwkam** [ciderapp/Cider#1601]
### Describe the Bug

Some pages refuse to load or show anything except for the "Browse" section, but I can play songs normally.
The heart/like buttons are sorta greyed out for songs too, and whenever I click on create a new playlist, it actually doesn't do anything.

### Steps to Reproduce

Just installed the app normally from the AUR and that's what I encounter after installing it.

### Environment Information

- OS: EndeavourOS
- Desktop Environment: XFCE
- App Version: Latest
- Commit ID:

### How did you download the software?

AUR

### Anything else?

![image](https://user-images.githubusercontent.com/91009118/206933565-daedac66-f0e9-4596-b755-18b9eb1034f8.png)
![image](https://user-images.githubusercontent.com/91009118/206933572-d9db1deb-97e1-41e8-842b-306009e56daf.png)
![image](https://user-images.githubusercontent.com/91009118/206933589-f71dd8a3-1a5c-407e-889d-752f5237c293.png)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Try a clean install of the app. You can find our guide on this [here](https://cider.gitbook.io/welcome-to-gitbook/support/troubleshooting).

**Comment by rsramkis** [comment]
Hi,

I'm also using Endeavour OS but with Gnome Desktop and Cider Flatpak. 

**Question:**

1. Are you using the Flatpak version?
2. What happens if you log out of your  Apple account in Cider, then log back in?
3. Is the issue sporatically happening (example for me everything was working fine this morning. Then this evening I had "Recently Played" and "Your Artist Feed" just have spinners trying to load something. I relaunched Cider a 3ed time and not I have most information like below:

![image](https://user-images.githubusercontent.com/14362317/214756817-14701d55-d4ac-4772-8bb2-73ef5fda4b05.png)
