### ISSUE TITLE
[Bug]: Discord Rich Presence is not working properly

### ISSUE THREAD

**Issue by ThiccRose** [ciderapp/Cider#1631]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.

### Cider Version

1.6,0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 21H2

### Where did you download Cider from?

GitHub

### Describe the Bug

Discord Rich Presence freezes in a song, even though I turned off in settings. It was working fine and I changed the application name from Cider to Apple music. In Discord it still says Cider. Turned off buttons too but seems like it frozen. 

![Capture](https://user-images.githubusercontent.com/83789493/211558236-0d2f3278-e052-4907-9561-f357c1ce2fcb.PNG)

Its not going away now, I tried restarting Cider, Discord and PC.

### Steps to Reproduce

After changed the application name to Apple Music
![Capture](https://user-images.githubusercontent.com/83789493/211558890-bdb038a4-49a1-464e-bf6b-85ea24c16cfd.PNG)

### Anything else?

Here are my logs [Logfiles.txt](https://github.com/ciderapp/Cider/files/10382946/Logfiles.txt)

**Comment by coredev-uk** [comment]
When you change the client name you need to restart Cider for the changes to apply, this is because it needs to reinitialise the discord-rpc interface with the new client name. If your discord-rpc freezes up, try clicking the reload DiscordRPC option in the connectivity settings menu. Sometimes it may take a bit to update in Discord as it can be slow at times.

Other than the above, there isn't really much more I can offer. Usually restarting both Discord and Cider resolves issues with RPC. If the RPC ever fails to connect consult our [docs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing).
