### ISSUE TITLE
[Bug]: Lossless isn't working for users on the discord

### ISSUE THREAD

**Issue by GamingLiamStudios** [ciderapp/Cider#337]
### Describe the Bug

So according to `Itsa Me, (m)Ario!!#6735` & some other users on the discord, they aren't getting ALAC, but 256kbps AAC instead.
Might require some investigating, as if this is true, then there is a pretty big problem with Lossless support.

### Steps to Reproduce

I [Ario] compiled the app with the latest commit, and installed the .deb package.
Switched to the `Lossless` Audio Quality setting & enabled `Decrypt Lossless Playback Workflow`
Restarted Cider
Looked at a song manifest, saw that it was still AAC

### Environment Information

- OS: Pop!_OS 21.10
- App Version: 1.1.0
- Commit ID: 2f75431

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yarrm80s** [comment]
Itsa Me, (m)Ario!!#6735 here, also to add to this, the lossless icon appeared when playing tracks (I made sure it's the correct one by checking the code. Also, it wasn't just the manifest that pointed out it was AAC, but the actual fragmented MP4 stream too which was clearly AAC.

Here's an example of one of the manifests I got: https://aod-ssl.itunes.apple.com/itunes-assets/Music128/v4/e5/f5/ff/e5f5ff79-edb1-8dac-3a32-b0e0408e2fca/mzaf_A1235474551.rphq.aac.wa.m3u8

I've tried restarting the app, tried tons of different songs, changing some settings that were related, etc and I could clearly see it was only getting AAC even though it was saying it was lossless (which I'm guessing is because the check for the lossless icon was just to see if the track supported it and if it was enabled in the app iirc), but it wasn't even trying to get the ALAC codec (it wasn't even getting the enhancedHls manifest, just a different AAC manifest)

**Comment by yarrm80s** [comment]
From someone on the team: "so basically the gist being that people aren't switching from AME because the 990kbps option was missing (which it never did existed in the first place) and so I proposed an elaborate scheme of lossless v2 on Cider. I took several hours to tune the processing so people can think it is not placebo (also that it takes minimum overhead on your cpu)"

Pretty sad that it was literally just lying

**Comment by GamingLiamStudios** [comment]
I'm going to close this as it isn't a bug anymore.
