### ISSUE TITLE
[Enhancement]: Airplay 2

### ISSUE THREAD

**Issue by harrisck** [ciderapp/Cider#384]
### The feature you would like

Being able to select an Airplay speaker (or mulltiple speakers) as an output device like you can in iTunes would be a great addition.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
We can do Airplay 1 and Chromecast, but Airplay 2 is complicated.

Airplay 2 requires the application to become a HomeKit hub and "pair" with each speaker. This would cause way too much overhead along with tanking our stability.

**Comment by grolschie** [comment]
Just a comment: Airplay actually seems to work nicely with Sony STR-DN1080 AV receiver (even though the app says "Homepods only for now". I haven't set a PIN though. I can see album artwork, but no artist/title/album text. I don't recall seeing album artwork when using Spotify:Connect with this AVR, so well done!

**Comment by vapormusic** [comment]
> Just a comment: Airplay actually seems to work nicely with Sony STR-DN1080 AV receiver (even though the app says "Homepods only for now". I haven't set a PIN though. I can see album artwork, but no artist/title/album text. I don't recall seeing album artwork when using Spotify:Connect with this AVR, so well done!

It's a AirPlay 1 speaker

**Comment by AxelTerizaki** [comment]
Seeing as this is closed, is there absolutely no way this is going to be implemented? I'd like to multicast my music to different speakers as well.

**Comment by vapormusic** [comment]
> Seeing as this is closed, is there absolutely no way this is going to be implemented? I'd like to multicast my music to different speakers as well.

Hmm AirPlay2 and multiroom is supported in Cider as of 1.5.6

**Comment by AxelTerizaki** [comment]
I've been trying Cider again, this time on LInux as it's still unusable for me on Windows (see #1262) but as I see it, the multicast feature isn't working well. Possibly because it's Airplay 1 right now, but I've been trying to multicast to both an Homepod (1st gen) and a Bose Soundbar 700 and while it indeed works, the sound has a slight delay on one of the speakers, which makes it unpleasant to listen to.

I suppose this "audio sync" feature is airplay 2 only?
