### ISSUE TITLE
[BUG] Shuffling Bug (unclear)

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Cider#41]
for example, if I want to play the song Bad Girls in my Shazam playlist, I have to go to the song Eternal Youth so I can play Bad Girls. This is quite confusing. Also, there is the problem when I have random mode on and want to listen to a specific song, I usually go to the song and click on it. But now it plays me a completely different song. My understanding of the mode is that when I skip the song I get a random song, but when I click on a specific one I also want it to play. This only happens when I move the app from my big screen to the small one. 
![grafik](https://user-images.githubusercontent.com/95378207/147505561-da563a3b-7eeb-44b9-bfd4-d2dca5f46dc2.png)

**Comment by coredev-uk** [comment]
There is no logic for in this 'if I want to play the song Bad Girls in my Shazam playlist, I have to go to the song Eternal Youth so I can play Bad Girls.', and the other thing your on about with shuffle mode, it's not very clear what the issue is, when you play a song with shuffle on it should play it and then the next song will be a random one in that album/playlist.

**Comment by Itsredsect** [comment]
Yeah it sounds strange,  it  happens.

**Comment by coredev-uk** [comment]
That still doesn't help. Could you be more clear with how you ended up causing this issue with shuffling?
