### ISSUE TITLE
[Bug]: Albums and Smart Playlist not showing up

### ISSUE THREAD

**Issue by samirodp** [ciderapp/Cider#541]
### Describe the Bug

I'm having issues with the app. I'm using the Microsoft Store version. My albums doesn't appear in my library neither my smart playlists. I sign out and sign in over a over, and I also re installed the app, but nothing changed.

### Steps to Reproduce

...

### Environment Information

Windows 11

### Anything else?

I contacted support in the Discord server, first they said that it was because Apple Music was having issues, after a couple days, the issues are still there, I contacted them again, and now I'm not having a response anymore.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nosh118** [comment]
Smart playlists unfortunately aren't supported at the moment due to the limitations of Apple's API, there's no way to get around that at the moment. Have you tried installing a develop build instead? I'll attach a link here ([https://944-429851205-gh.circle-artifacts.com/0/~/Cider/dist/artifacts/Cider-Setup-1.2.944.exe](https://944-429851205-gh.circle-artifacts.com/0/~/Cider/dist/artifacts/Cider-Setup-1.2.944.exe)), let me know if it solves the albums issue. If it does, it's likely that when the next update gets pushed to the Microsoft Store version, it will be fixed. Remember, the app's still in Alpha 😉.

**Comment by coredev-uk** [comment]
#402

**Comment by samirodp** [comment]
> Smart playlists unfortunately aren't supported at the moment due to the limitations of Apple's API, there's no way to get around that at the moment. Have you tried installing a develop build instead? I'll attach a link here (https://944-429851205-gh.circle-artifacts.com/0/~/Cider/dist/artifacts/Cider-Setup-1.2.944.exe), let me know if it solves the albums issue. If it does, it's likely that when the next update gets pushed to the Microsoft Store version, it will be fixed. Remember, the app's still in Alpha 😉.

Thanks! I installed the develop build but it is still not working. My albums are still not showing up, and also the artists and recently added sections are empty.
