### ISSUE TITLE
[Bug]: last fm connect broken

### ISSUE THREAD

**Issue by 3hree6ix0** [ciderapp/Cider#571]
### Last.fm scrobbler

Trying to connect last fm scrobbler

steps i did;
1. Settings > connect last fm
2. opens in browser, press allow access, 
3. asks for xdg-open cider, click xdg-open
4. button in cider says connecting for a few secs nothing happens to the allow page doesnt connect.

### Steps to Reproduce

1. connect lastfm button
2. click on xdg-open in browser

### Environment Information

- OS: Endeavour OS Atlantis
- App Version: aur version (cider-git lastest version)
- Commit ID:

### Anything else?

One more thing i tried was to delete all config files and put them on again, didnt work.
Also tried switching wm/de from hlwm to xfce.
tried different browser, didnt work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Probably a protocol issue as I've known the AUR package to cause issues with this. Anyone with knowledge in mimetypes and protocols on Linux, some help would be great.

**Comment by gkeep** [comment]
This issue is not present in AppImage releases.

Here's how you can work around this bug:
1. download an AppImage release
2. integrate it with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) (so you can open the redirect link with the AppImage release) 
3. start connecting Last.FM as usual 
4. select the AppImage release in xdg-open dialog. It will have a version number in parenthesis: *Cider (X.Y.ZZZZ)*

Now you can remove the AppImage release and AppImageLauncher.

If you're using native packages (deb/AUR) you're done!

And if you're using the Flatpak release you need to replace the `~/.var/app/sh.cider.Cider/config/Cider` folder with `~/.config/Cider`:
1. delete the `~/.var/app/sh.cider.Cider/config/Cider` folder 
2. copy/move `~/.config/Cider` folder to `~/.var/app/sh.cider.Cider/config/Cider`.

Same goes for snap, but I don't know where it keeps the app's configs.

**Comment by money5240** [comment]
https://github.com/ciderapp/Cider/runs/5779643464?check_suite_focus=true
