### ISSUE TITLE
[Bug]: MacOS space bar issues-

### ISSUE THREAD

**Issue by ghost** [ciderapp/Cider#728]
### Describe the Bug

 when you click the space bar to pause (im on macos) if i had just skipped a song it auto defaults to the space bar skipping a song instead of pausing

### Steps to Reproduce

read above

### Environment Information

- OS: macOS
- App Version and/or Commit ID: 1.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quasigod-io** [comment]
This issue also appears on Linux. Switching to the cider window and pressing space will select whichever item is always selected instead of pausing. I believe this should be changed so that space always pauses and only enter presses the selected item.

Even if pause was most recently selected, space will pause when it is pressed down, and unpause when raised. Clicking an empty part of the app will allow space to pause the song.
