### ISSUE TITLE
[Bug]: "Crackly and static" music with Maikiwi Audio Lab settings

### ISSUE THREAD

**Issue by calum523** [ciderapp/Cider#737]
### Describe the Bug

music static and crackly when browsing anywhere in the app apart from settings

### Steps to Reproduce

listen to music with the mekaiki audio lab settings on

### Environment Information

- OS: macOS
- App Version and/or Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amaru8** [comment]
@calum523, please try the latest build of Cider. I tried Cider on a 2020 M1 MacBook Air like a week ago, it didn't have any issues with the Audio Lab features.

**Comment by grolschie** [comment]
I have the same issue, I think. After enabling the "Enable Advanced Functionality" and playing with the features, the audio starts to stutter when scrolling in the app with the mouse. Stop scrolling, and it's _mostly_ fine. To be fair, I get the message "Cider thinks your PC can't handle these features" when enabling it though. System is: Dell XPS 13 9360, Windows 11, i7-7500u, 8GB RAM, 256GM SSD, Intel HD 620 integrated graphics. Cider 1.4.5 (Microsoft Store version).

**Comment by maikirakiwi** [comment]
I’m 500% sure it’s because of the complexity of Cider Audio Lab that makes low end PC stutter. (This includes any Mac that’s not recent enough)

Any Mac manufactured post 2017 should have no problem given you don’t have other resource intensive apps open.
Apple Silicon Mac will also handle Cider gracefully with no issue.
