### ISSUE TITLE
[Bug]: Songs are stopped playing

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Cider#743]
### Describe the Bug

When playing songs, Cider randomly stops in the middle of the song. Pushing Play, Next Track and Previous Track button has no effect. Only solution is CTRL + R or restart of the app

### Steps to Reproduce

Play a song
It stops in the middle of the current song or it happens after several songs.

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.4.0 Alpha 1606

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aideya** [comment]
I have also been experiencing this issue. Log provided below. For me, it is nearly always right at the start of a song (within the first 2 sec) and it's never the first song. I also have to restart the app to get anything to play at this point. 

It occurs within around 5 songs of initial play. Most certainly always occurs before the 10th song.

I have not tested extensively so take this with a grain of salt but it seems to happen more with playlists/radios than with an album in normal order (on shuffle it's just as bad as a playlist).

OS: Windows 10 version 21H2 Build 19044.1586

App Version: 1.40

NOTE: I have experienced this issue since before 1.40 so I doubt it's a newly introduced bug.

[CiderLog.txt](https://github.com/ciderapp/Cider/files/8385438/CiderLog.txt)

**Comment by xx88xx** [comment]
https://github.com/ciderapp/Cider/issues/693

Can merge these
