### ISSUE TITLE
[Bug]: Filter "Date Added" is wrong sorting the list music. 

### ISSUE THREAD

**Issue by victordosanjos** [ciderapp/Cider#763]
### Describe the Bug

Using "date added' filter to sort music by last added music is not properly putting on the position.

### Steps to Reproduce

1. Go to Songs
2. Mark "Date Added"  

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.4.0-alpha.1626

### Anything else?

My musics sorted by "date added" [here](https://user-images.githubusercontent.com/54488860/160968428-bf2e8dc6-1d70-473c-b3be-34763294c087.png)
And the same on itunes [here](https://user-images.githubusercontent.com/54488860/160968448-d8c150f6-8358-47fe-b6b4-759e6db6eb49.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by or-agami** [comment]
Hi, I just downloaded the app from Microsoft store, from what I can see sorting by Date Added do not change the sorting, it's just stays in the previous sorting option

**Comment by victordosanjos** [comment]
> 

They didn't modify this thread but in the last nightly build its already fix it. You can install it using winget.

**Comment by victordosanjos** [comment]
> Hi, I just downloaded the app from Microsoft store, from what I can see sorting by Date Added do not change the sorting, it's just stays in the previous sorting option


They didn't modify this thread but in the last nightly build its already fix it. You can install it using winget.

**Comment by rursache** [comment]
> @victordosanjos They didn't modify this thread but in the last nightly build its already fix it. You can install it using winget.
i've build it from source (develop branch) and the issue is still there

**Comment by Amaru8** [comment]
# Additional Info

**Okay, so when I save a song, from an album I already have a song in my library, it thinks I saved all of the songs I have from that album at the same time.**

# For example:

- I saved _Song 3_ and _Song 4_ from _Album X_ to my library on _January 11._
- I save _Song 1_ from _Album X_ to my library on _April 9._

## Result (on April 9.):

### Cider:

- **Song 3** - Album X
- **Song 4** - Album X
- **Song 1** - Album X
- **other songs i listened to**

## Expected Behaviour

- **Song 1** - Album X
- **other songs i listened to**
- **Song 3** - Album X
- **Song 4** - Album X

# Config

- OS Version: `Windows 11 Home`
- App Version: `Cider Version 1.4.2 - Build 1746 (develop)`

**Comment by austinthetaco** [comment]
This bug still persists. Sorting by date added is doing nothing. I added a song from a random radio to my list, then went to my library, refreshed it, and sorted by date added. Song I JUST added is smack dab in the middle.

**Comment by timleeds15** [comment]
Still not fixed. What gives :/

**Comment by cryptofyre** [comment]
We're in the process of writing brand new code for Cider 2.x. This fix will be included in the rewrite.
