### ISSUE TITLE
[Bug]: Albums not loading

### ISSUE THREAD

**Issue by DankeBrutus** [ciderapp/Cider#883]
### Describe the Bug

When trying to load albums on the bottom left the message says updating albums. However, it immediately jumps to 100/660 and then the message disappears.

### Steps to Reproduce

1. Click "Albums"
2. Click the refresh button on the top right.

### Environment Information

- OS: Linux (Fedora 35 - kernel 5.16.18)
- App Version and/or Commit ID: Flatpak v.1.4.3.1784

### Anything else?

![Screenshot from 2022-04-16 12-52-21](https://user-images.githubusercontent.com/77204422/163684255-026a28d5-6c5a-49d3-9b41-b9523eda210a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rowbawts** [comment]
I'm on the same distro and same Cider version (also Flatpak) and it works for me so that's interesting.

PS: I'm the Flatpak maintainer so I'll help fix this if its a Flatpak issue.

![Screenshot from 2022-04-16 13-05-47](https://user-images.githubusercontent.com/13012832/163684543-06acd204-ce11-4971-aa0e-46ac11ea2a9b.png)

**Comment by DankeBrutus** [comment]
I have tried logging out and logging in again, I've also tried reinstalling the Cider flatpak. Albums and artists still remain empty. Songs load fine. Home loads, recently added does not, playlists do load. 

If there is more information needed let me know.

**Comment by SlimShadyIAm** [comment]
I have the same issue

**Comment by cryptofyre** [comment]
This is Apple having server issues. Happens on randomly and quite commonly unfortunately.
